# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'practica 1wwKkxW.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QMenuBar,
    QProgressBar, QPushButton, QScrollBar, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(736, 553)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.cmdSalir = QPushButton(self.centralwidget)
        self.cmdSalir.setObjectName(u"cmdSalir")
        self.cmdSalir.setGeometry(QRect(650, 460, 75, 31))
        font = QFont()
        font.setBold(True)
        self.cmdSalir.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(320, 20, 51, 31))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.label.setFont(font1)
        self.btnLed1 = QPushButton(self.centralwidget)
        self.btnLed1.setObjectName(u"btnLed1")
        self.btnLed1.setGeometry(QRect(70, 20, 75, 31))
        self.btnLed1.setFont(font1)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(180, 20, 71, 31))
        self.label_2.setFont(font1)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 20, 47, 31))
        self.label_3.setFont(font1)
        self.lblBoton1 = QLabel(self.centralwidget)
        self.lblBoton1.setObjectName(u"lblBoton1")
        self.lblBoton1.setGeometry(QRect(260, 20, 31, 31))
        self.lblBoton1.setFont(font1)
        self.barAdc1 = QProgressBar(self.centralwidget)
        self.barAdc1.setObjectName(u"barAdc1")
        self.barAdc1.setGeometry(QRect(370, 20, 311, 31))
        self.barAdc1.setMaximum(4095)
        self.barAdc1.setValue(0)
        self.cmdConectar = QPushButton(self.centralwidget)
        self.cmdConectar.setObjectName(u"cmdConectar")
        self.cmdConectar.setGeometry(QRect(550, 460, 75, 31))
        self.cmdConectar.setFont(font)
        self.btnLed2 = QPushButton(self.centralwidget)
        self.btnLed2.setObjectName(u"btnLed2")
        self.btnLed2.setGeometry(QRect(70, 60, 75, 31))
        self.btnLed2.setFont(font1)
        self.btnLed3 = QPushButton(self.centralwidget)
        self.btnLed3.setObjectName(u"btnLed3")
        self.btnLed3.setGeometry(QRect(70, 100, 75, 31))
        self.btnLed3.setFont(font1)
        self.btnLed4 = QPushButton(self.centralwidget)
        self.btnLed4.setObjectName(u"btnLed4")
        self.btnLed4.setGeometry(QRect(70, 140, 75, 31))
        self.btnLed4.setFont(font1)
        self.btnLed5 = QPushButton(self.centralwidget)
        self.btnLed5.setObjectName(u"btnLed5")
        self.btnLed5.setGeometry(QRect(70, 180, 75, 31))
        self.btnLed5.setFont(font1)
        self.btnLed8 = QPushButton(self.centralwidget)
        self.btnLed8.setObjectName(u"btnLed8")
        self.btnLed8.setGeometry(QRect(70, 300, 75, 31))
        self.btnLed8.setFont(font1)
        self.btnLed7 = QPushButton(self.centralwidget)
        self.btnLed7.setObjectName(u"btnLed7")
        self.btnLed7.setGeometry(QRect(70, 260, 75, 31))
        self.btnLed7.setFont(font1)
        self.btnLed6 = QPushButton(self.centralwidget)
        self.btnLed6.setObjectName(u"btnLed6")
        self.btnLed6.setGeometry(QRect(70, 220, 75, 31))
        self.btnLed6.setFont(font1)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 60, 47, 31))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 100, 47, 31))
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 140, 47, 31))
        self.label_6.setFont(font1)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 180, 47, 31))
        self.label_7.setFont(font1)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 220, 47, 31))
        self.label_8.setFont(font1)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 260, 47, 31))
        self.label_9.setFont(font1)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 290, 47, 31))
        self.label_10.setFont(font1)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(180, 60, 71, 31))
        self.label_11.setFont(font1)
        self.lblBoton2 = QLabel(self.centralwidget)
        self.lblBoton2.setObjectName(u"lblBoton2")
        self.lblBoton2.setGeometry(QRect(260, 60, 31, 31))
        self.lblBoton2.setFont(font1)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(180, 100, 71, 31))
        self.label_12.setFont(font1)
        self.lblBoton3 = QLabel(self.centralwidget)
        self.lblBoton3.setObjectName(u"lblBoton3")
        self.lblBoton3.setGeometry(QRect(260, 100, 31, 31))
        self.lblBoton3.setFont(font1)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(180, 150, 71, 31))
        self.label_13.setFont(font1)
        self.lblBoton4 = QLabel(self.centralwidget)
        self.lblBoton4.setObjectName(u"lblBoton4")
        self.lblBoton4.setGeometry(QRect(260, 150, 31, 31))
        self.lblBoton4.setFont(font1)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(180, 260, 71, 31))
        self.label_14.setFont(font1)
        self.lblBoton7 = QLabel(self.centralwidget)
        self.lblBoton7.setObjectName(u"lblBoton7")
        self.lblBoton7.setGeometry(QRect(260, 260, 31, 31))
        self.lblBoton7.setFont(font1)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(180, 300, 71, 31))
        self.label_15.setFont(font1)
        self.lblBoton8 = QLabel(self.centralwidget)
        self.lblBoton8.setObjectName(u"lblBoton8")
        self.lblBoton8.setGeometry(QRect(260, 300, 31, 31))
        self.lblBoton8.setFont(font1)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(180, 220, 71, 31))
        self.label_16.setFont(font1)
        self.lblBoton6 = QLabel(self.centralwidget)
        self.lblBoton6.setObjectName(u"lblBoton6")
        self.lblBoton6.setGeometry(QRect(260, 220, 31, 31))
        self.lblBoton6.setFont(font1)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(180, 180, 71, 31))
        self.label_17.setFont(font1)
        self.lblBoton5 = QLabel(self.centralwidget)
        self.lblBoton5.setObjectName(u"lblBoton5")
        self.lblBoton5.setGeometry(QRect(260, 180, 31, 31))
        self.lblBoton5.setFont(font1)
        self.barAdc2 = QProgressBar(self.centralwidget)
        self.barAdc2.setObjectName(u"barAdc2")
        self.barAdc2.setGeometry(QRect(370, 60, 311, 31))
        self.barAdc2.setMaximum(4095)
        self.barAdc2.setValue(0)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(320, 60, 51, 31))
        self.label_18.setFont(font1)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(310, 90, 61, 31))
        self.label_19.setFont(font1)
        self.barAdc3 = QProgressBar(self.centralwidget)
        self.barAdc3.setObjectName(u"barAdc3")
        self.barAdc3.setGeometry(QRect(370, 90, 311, 31))
        self.barAdc3.setMaximum(4095)
        self.barAdc3.setValue(0)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(310, 130, 61, 31))
        self.label_20.setFont(font1)
        self.barAdc4 = QProgressBar(self.centralwidget)
        self.barAdc4.setObjectName(u"barAdc4")
        self.barAdc4.setGeometry(QRect(370, 130, 311, 31))
        self.barAdc4.setMaximum(4095)
        self.barAdc4.setValue(0)
        self.scbPwm1 = QScrollBar(self.centralwidget)
        self.scbPwm1.setObjectName(u"scbPwm1")
        self.scbPwm1.setGeometry(QRect(330, 230, 231, 41))
        self.scbPwm1.setMaximum(255)
        self.scbPwm1.setOrientation(Qt.Orientation.Horizontal)
        self.scbPwm2 = QScrollBar(self.centralwidget)
        self.scbPwm2.setObjectName(u"scbPwm2")
        self.scbPwm2.setGeometry(QRect(330, 310, 221, 41))
        self.scbPwm2.setMaximum(255)
        self.scbPwm2.setOrientation(Qt.Orientation.Horizontal)
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(320, 280, 61, 31))
        self.label_21.setFont(font1)
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(320, 200, 61, 31))
        self.label_22.setFont(font1)
        self.lblpwm1 = QLabel(self.centralwidget)
        self.lblpwm1.setObjectName(u"lblpwm1")
        self.lblpwm1.setGeometry(QRect(500, 240, 61, 31))
        self.lblpwm1.setFont(font1)
        self.lblpwm2 = QLabel(self.centralwidget)
        self.lblpwm2.setObjectName(u"lblpwm2")
        self.lblpwm2.setGeometry(QRect(500, 300, 61, 31))
        self.lblpwm2.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 736, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.cmdSalir.setText(QCoreApplication.translate("MainWindow", u"SALIR", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"ADC 1: ", None))
        self.btnLed1.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"BOTON 1:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"LED 1:", None))
        self.lblBoton1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.cmdConectar.setText(QCoreApplication.translate("MainWindow", u"CONECTAR", None))
        self.btnLed2.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.btnLed3.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.btnLed4.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.btnLed5.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.btnLed8.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.btnLed7.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.btnLed6.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"LED 2:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"LED 3: ", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"LED 4:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"LED 5:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"LED 6:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"LED 7:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"LED 8:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"BOTON 2:", None))
        self.lblBoton2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"BOTON 3:", None))
        self.lblBoton3.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"BOTON 4:", None))
        self.lblBoton4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"BOTON 7:", None))
        self.lblBoton7.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"BOTON 8:", None))
        self.lblBoton8.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"BOTON 6:", None))
        self.lblBoton6.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"BOTON 5:", None))
        self.lblBoton5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"ADC 2: ", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"ADC 3", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"ADC 4 ", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"PWM 2:", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"PWM 1:", None))
        self.lblpwm1.setText("")
        self.lblpwm2.setText("")
    # retranslateUi

